# Real Gemini AI Test - Create Annual Target with AI Planning
Write-Host "=" * 100 -ForegroundColor Cyan
Write-Host "  TESTING GEMINI AI - ANNUAL TARGET WITH 48-WEEK PLAN GENERATION" -ForegroundColor Green
Write-Host "=" * 100 -ForegroundColor Cyan
Write-Host ""

$baseUrl = "http://localhost:5041"

# Step 1: Login as Manager
Write-Host "STEP 1: LOGIN AS MANAGER" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray

$loginBody = @{
    emailOrPhone = "manager@rafeed.com"
    password = "manager123"
} | ConvertTo-Json

try {
    $loginResponse = Invoke-RestMethod -Uri "$baseUrl/api/v1/auth/login" -Method Post -Body $loginBody -ContentType "application/json"
    $token = $loginResponse.token
    Write-Host "   SUCCESS - Logged in" -ForegroundColor Green
    Write-Host "   Manager: $($loginResponse.user.fullName)" -ForegroundColor White
    Write-Host "   Email: $($loginResponse.user.email)" -ForegroundColor White
    Write-Host ""
} catch {
    Write-Host "   FAILED - Cannot login" -ForegroundColor Red
    Write-Host "   Error: $($_.Exception.Message)" -ForegroundColor Red
    if ($_.ErrorDetails) {
        Write-Host "   Details: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host ""
    exit 1
}

$headers = @{
    "Authorization" = "Bearer $token"
    "Content-Type" = "application/json"
}

# Step 2: Create Annual Target (This triggers Gemini AI!)
Write-Host "STEP 2: CREATE ANNUAL TARGET - GEMINI AI WILL GENERATE 48-WEEK PLAN" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray
Write-Host ""
Write-Host "Sending request to Gemini AI..." -ForegroundColor Cyan
Write-Host "This may take 10-30 seconds as AI generates the complete plan..." -ForegroundColor Cyan
Write-Host ""

$annualTargetBody = @{
    targetYear = 2026
    totalTargetRevenue = 1000000.0
    description = "Annual revenue target for 2026 - Complete AI Planning Test"
} | ConvertTo-Json

Write-Host "Request Body:" -ForegroundColor Yellow
Write-Host $annualTargetBody -ForegroundColor White
Write-Host ""

try {
    Write-Host "Calling API... (Gemini AI is working in the background)" -ForegroundColor Cyan
    $startTime = Get-Date

    $result = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/annual-targets" -Method Post -Headers $headers -Body $annualTargetBody

    $endTime = Get-Date
    $duration = ($endTime - $startTime).TotalSeconds

    Write-Host ""
    Write-Host "=" * 100 -ForegroundColor Green
    Write-Host "  GEMINI AI SUCCESS!" -ForegroundColor Green
    Write-Host "=" * 100 -ForegroundColor Green
    Write-Host ""

    if ($result.success) {
        Write-Host "Response Time: $([math]::Round($duration, 2)) seconds" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "SUCCESS MESSAGE:" -ForegroundColor Green
        Write-Host "  $($result.message)" -ForegroundColor White
        Write-Host ""

        Write-Host "ANNUAL TARGET CREATED:" -ForegroundColor Yellow
        Write-Host "  ID: $($result.data.id)" -ForegroundColor White
        Write-Host "  Year: $($result.data.targetYear)" -ForegroundColor White
        Write-Host "  Total Target Revenue: `$$($result.data.totalTargetRevenue)" -ForegroundColor White
        Write-Host "  Description: $($result.data.description)" -ForegroundColor White
        Write-Host ""

        # Check Monthly Plans
        $monthlyCount = $result.data.monthlyPlans.Count
        Write-Host "MONTHLY PLANS GENERATED BY GEMINI AI:" -ForegroundColor Yellow
        Write-Host "  Count: $monthlyCount months" -ForegroundColor $(if ($monthlyCount -eq 12) {"Green"} else {"Red"})
        Write-Host ""

        if ($monthlyCount -gt 0) {
            Write-Host "  Monthly Breakdown:" -ForegroundColor Cyan
            foreach ($month in $result.data.monthlyPlans) {
                Write-Host "    Month $($month.month): Target = `$$($month.targetRevenue), Weeks = $($month.weeklyPlans.Count)" -ForegroundColor White
            }
            Write-Host ""
        }

        # Count Weekly Plans
        $weeklyCount = 0
        foreach ($month in $result.data.monthlyPlans) {
            $weeklyCount += $month.weeklyPlans.Count
        }

        Write-Host "WEEKLY PLANS GENERATED BY GEMINI AI:" -ForegroundColor Yellow
        Write-Host "  Count: $weeklyCount weeks" -ForegroundColor $(if ($weeklyCount -eq 48) {"Green"} else {"Red"})
        Write-Host ""

        if ($weeklyCount -gt 0) {
            Write-Host "  First Few Weeks:" -ForegroundColor Cyan
            $weekNum = 1
            foreach ($month in $result.data.monthlyPlans) {
                foreach ($week in $month.weeklyPlans) {
                    if ($weekNum -le 5) {
                        Write-Host "    Week $weekNum (Month $($month.month)): Target = `$$($week.targetRevenue)" -ForegroundColor White
                    }
                    $weekNum++
                }
            }
            Write-Host "    ... and $($weeklyCount - 5) more weeks" -ForegroundColor Gray
            Write-Host ""
        }

        Write-Host "=" * 100 -ForegroundColor Green
        Write-Host ""
        Write-Host "GEMINI AI VERIFICATION:" -ForegroundColor Yellow
        Write-Host ""

        if ($monthlyCount -eq 12 -and $weeklyCount -eq 48) {
            Write-Host "  ✅ GEMINI AI IS WORKING PERFECTLY!" -ForegroundColor Green
            Write-Host "  ✅ Generated 12 monthly plans" -ForegroundColor Green
            Write-Host "  ✅ Generated 48 weekly plans" -ForegroundColor Green
            Write-Host "  ✅ Revenue distribution complete" -ForegroundColor Green
            Write-Host ""
            Write-Host "  Your Gemini AI integration is 100% functional! 🎉" -ForegroundColor Green
        } else {
            Write-Host "  ⚠️ Unexpected plan count" -ForegroundColor Yellow
            Write-Host "  Expected: 12 months, 48 weeks" -ForegroundColor Yellow
            Write-Host "  Got: $monthlyCount months, $weeklyCount weeks" -ForegroundColor Yellow
        }

        Write-Host ""
        Write-Host "=" * 100 -ForegroundColor Green

        # Store IDs for further testing
        $script:annualTargetId = $result.data.id
        $script:monthlyPlanId = $result.data.monthlyPlans[0].id
        $script:weeklyPlanId = $result.data.monthlyPlans[0].weeklyPlans[0].id

        Write-Host ""
        Write-Host "TESTING ADDITIONAL GEMINI AI ENDPOINTS..." -ForegroundColor Yellow
        Write-Host ""

        # Test 3: Create a Task for AI Analysis
        Write-Host "STEP 3: CREATE TASK FOR AI ANALYSIS" -ForegroundColor Yellow
        Write-Host "-" * 100 -ForegroundColor Gray

        $taskBody = @{
            weeklyPlanId = $script:weeklyPlanId
            taskName = "Implement Payment Gateway Integration"
            description = "Complete integration with MyFatoorah payment gateway including ExecutePayment, InitiatePayment, and callback handling"
            priority = "High"
            estimatedHours = 40
            dueDate = (Get-Date).AddDays(7).ToString("yyyy-MM-ddTHH:mm:ss")
        } | ConvertTo-Json

        try {
            $taskResult = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/tasks" -Method Post -Headers $headers -Body $taskBody

            if ($taskResult.success) {
                Write-Host "   ✅ Task Created: $($taskResult.data.taskName)" -ForegroundColor Green
                Write-Host "   Task ID: $($taskResult.data.id)" -ForegroundColor White
                Write-Host ""

                $taskId = $taskResult.data.id

                # Test 4: Analyze Task with Gemini AI
                Write-Host "STEP 4: ANALYZE TASK WITH GEMINI AI" -ForegroundColor Yellow
                Write-Host "-" * 100 -ForegroundColor Gray
                Write-Host ""
                Write-Host "Sending task to Gemini AI for analysis..." -ForegroundColor Cyan

                try {
                    $analysisResult = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/tasks/$taskId/analyze" -Method Post -Headers $headers

                    if ($analysisResult.success) {
                        Write-Host ""
                        Write-Host "=" * 100 -ForegroundColor Green
                        Write-Host "  GEMINI AI TASK ANALYSIS - SUCCESS!" -ForegroundColor Green
                        Write-Host "=" * 100 -ForegroundColor Green
                        Write-Host ""
                        Write-Host "AI Analysis for: $($analysisResult.data.taskName)" -ForegroundColor Yellow
                        Write-Host ""
                        Write-Host "Complexity: $($analysisResult.data.complexity)" -ForegroundColor Cyan
                        Write-Host "Estimated Hours: $($analysisResult.data.estimatedHours)" -ForegroundColor Cyan
                        Write-Host "Risk Level: $($analysisResult.data.riskLevel)" -ForegroundColor Cyan
                        Write-Host ""
                        Write-Host "Recommendations:" -ForegroundColor Yellow
                        Write-Host "$($analysisResult.data.recommendations)" -ForegroundColor White
                        Write-Host ""
                        Write-Host "Alternative Approaches:" -ForegroundColor Yellow
                        Write-Host "$($analysisResult.data.alternativeApproaches)" -ForegroundColor White
                        Write-Host ""
                        Write-Host "✅ GEMINI AI TASK ANALYSIS IS WORKING!" -ForegroundColor Green
                        Write-Host ""
                    }
                } catch {
                    Write-Host "   ⚠️ Task Analysis Error: $($_.Exception.Message)" -ForegroundColor Yellow
                }
            }
        } catch {
            Write-Host "   ⚠️ Task Creation Error: $($_.Exception.Message)" -ForegroundColor Yellow
        }

    } else {
        Write-Host "   FAILED" -ForegroundColor Red
        Write-Host "   Message: $($result.message)" -ForegroundColor Red
    }

} catch {
    Write-Host ""
    Write-Host "=" * 100 -ForegroundColor Red
    Write-Host "  GEMINI AI ERROR" -ForegroundColor Red
    Write-Host "=" * 100 -ForegroundColor Red
    Write-Host ""
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red

    if ($_.ErrorDetails) {
        Write-Host ""
        Write-Host "Details:" -ForegroundColor Yellow
        Write-Host "$($_.ErrorDetails.Message)" -ForegroundColor Red
    }

    Write-Host ""
    Write-Host "This could be due to:" -ForegroundColor Yellow
    Write-Host "  1. Gemini API key is invalid" -ForegroundColor White
    Write-Host "  2. Gemini API quota exceeded" -ForegroundColor White
    Write-Host "  3. Network connectivity issues" -ForegroundColor White
    Write-Host "  4. Subscription requirement not met" -ForegroundColor White
    Write-Host ""
}

Write-Host ""
Write-Host "=" * 100 -ForegroundColor Cyan
Write-Host "  TEST COMPLETE" -ForegroundColor Green
Write-Host "=" * 100 -ForegroundColor Cyan
