# Complete Gemini AI Testing Script
Write-Host "=" * 100 -ForegroundColor Cyan
Write-Host "  GEMINI AI COMPLETE TESTING" -ForegroundColor Green
Write-Host "=" * 100 -ForegroundColor Cyan
Write-Host ""

$baseUrl = "http://localhost:5041"

# Step 1: Login
Write-Host "STEP 1: AUTHENTICATION" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray

$loginBody = @{
    emailOrPhone = "manager@rafeed.com"
    password = "manager123"
} | ConvertTo-Json

try {
    $loginResponse = Invoke-RestMethod -Uri "$baseUrl/api/v1/auth/login" -Method Post -Body $loginBody -ContentType "application/json"
    $token = $loginResponse.token
    Write-Host "   SUCCESS - Logged in as: $($loginResponse.user.fullName)" -ForegroundColor Green
    Write-Host ""
} catch {
    Write-Host "   FAILED - Cannot login" -ForegroundColor Red
    exit 1
}

$headers = @{
    "Authorization" = "Bearer $token"
    "Content-Type" = "application/json"
}

# Step 2: Create Annual Target (This will trigger Gemini AI to generate 48 weeks)
Write-Host "STEP 2: CREATE ANNUAL TARGET (AI GENERATES 48-WEEK PLAN)" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray
Write-Host "This will use Gemini AI to automatically generate a complete 48-week plan" -ForegroundColor White
Write-Host ""

$annualTargetBody = @{
    targetYear = 2026
    totalTargetRevenue = 1000000.0
    description = "Annual revenue target for 2026 - AI Planning Test"
} | ConvertTo-Json

try {
    Write-Host "Creating annual target... (AI is working in the background)" -ForegroundColor Cyan
    $result = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/annual-targets" -Method Post -Headers $headers -Body $annualTargetBody

    if ($result.success) {
        Write-Host "   SUCCESS!" -ForegroundColor Green
        Write-Host "   Annual Target ID: $($result.data.id)" -ForegroundColor White
        Write-Host "   Target Revenue: `$$($result.data.totalTargetRevenue)" -ForegroundColor White
        Write-Host "   Year: $($result.data.targetYear)" -ForegroundColor White
        Write-Host "   Monthly Plans: $($result.data.monthlyPlans.Count)" -ForegroundColor Green

        $weeklyCount = 0
        foreach ($month in $result.data.monthlyPlans) {
            $weeklyCount += $month.weeklyPlans.Count
        }
        Write-Host "   Weekly Plans Generated by AI: $weeklyCount" -ForegroundColor Green
        Write-Host ""

        $annualTargetId = $result.data.id
        $monthlyPlanId = $result.data.monthlyPlans[0].id
        $weeklyPlanId = $result.data.monthlyPlans[0].weeklyPlans[0].id

        Write-Host "   Gemini AI successfully created the entire year's plan!" -ForegroundColor Green
        Write-Host ""
    } else {
        Write-Host "   FAILED: $($result.message)" -ForegroundColor Red
        Write-Host ""
        exit 1
    }
} catch {
    Write-Host "   ERROR: $($_.Exception.Message)" -ForegroundColor Red
    if ($_.ErrorDetails) {
        Write-Host "   Details: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host ""
    exit 1
}

# Step 3: Create a Task
Write-Host "STEP 3: CREATE TASK FOR AI ANALYSIS" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray

$taskBody = @{
    weeklyPlanId = $weeklyPlanId
    taskName = "Develop Electronic Payment System"
    description = "Develop complete payment integration with MyFatoorah including testing and documentation"
    priority = "High"
    estimatedHours = 40
    dueDate = (Get-Date).AddDays(7).ToString("yyyy-MM-ddTHH:mm:ss")
} | ConvertTo-Json

try {
    $taskResult = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/tasks" -Method Post -Headers $headers -Body $taskBody

    if ($taskResult.success) {
        Write-Host "   SUCCESS!" -ForegroundColor Green
        Write-Host "   Task ID: $($taskResult.data.id)" -ForegroundColor White
        Write-Host "   Task Name: $($taskResult.data.taskName)" -ForegroundColor White
        Write-Host ""

        $taskId = $taskResult.data.id
    } else {
        Write-Host "   FAILED: $($taskResult.message)" -ForegroundColor Red
        Write-Host ""
        exit 1
    }
} catch {
    Write-Host "   ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host ""
    exit 1
}

# Step 4: Analyze Task with Gemini AI
Write-Host "STEP 4: ANALYZE TASK WITH GEMINI AI" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray
Write-Host "Gemini AI will analyze complexity, risks, and provide recommendations..." -ForegroundColor White
Write-Host ""

try {
    $analysisResult = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/tasks/$taskId/analyze" -Method Post -Headers $headers

    if ($analysisResult.success) {
        Write-Host "   SUCCESS! AI Analysis Complete" -ForegroundColor Green
        Write-Host ""
        Write-Host "   AI Analysis Results:" -ForegroundColor Yellow
        Write-Host "   ===================" -ForegroundColor Yellow
        Write-Host "   Task: $($analysisResult.data.taskName)" -ForegroundColor White
        Write-Host "   Complexity: $($analysisResult.data.complexity)" -ForegroundColor Cyan
        Write-Host "   Estimated Hours: $($analysisResult.data.estimatedHours)" -ForegroundColor Cyan
        Write-Host "   Risk Level: $($analysisResult.data.riskLevel)" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "   Recommendations:" -ForegroundColor Yellow
        Write-Host "   $($analysisResult.data.recommendations)" -ForegroundColor White
        Write-Host ""
        Write-Host "   Alternative Approaches:" -ForegroundColor Yellow
        Write-Host "   $($analysisResult.data.alternativeApproaches)" -ForegroundColor White
        Write-Host ""
    } else {
        Write-Host "   FAILED: $($analysisResult.message)" -ForegroundColor Red
        Write-Host ""
    }
} catch {
    Write-Host "   ERROR: $($_.Exception.Message)" -ForegroundColor Red
    if ($_.ErrorDetails) {
        Write-Host "   Details: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host ""
}

# Step 5: Batch Analyze Tasks
Write-Host "STEP 5: BATCH ANALYZE MULTIPLE TASKS" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray

$batchBody = @($taskId) | ConvertTo-Json

try {
    $batchResult = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/tasks/analyze-batch" -Method Post -Headers $headers -Body $batchBody -ContentType "application/json"

    if ($batchResult.success) {
        Write-Host "   SUCCESS! Batch Analysis Complete" -ForegroundColor Green
        Write-Host "   Tasks Analyzed: $($batchResult.data.Count)" -ForegroundColor White
        Write-Host ""
    } else {
        Write-Host "   FAILED: $($batchResult.message)" -ForegroundColor Red
        Write-Host ""
    }
} catch {
    Write-Host "   ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host ""
}

# Step 6: Generate Weekly Performance Report
Write-Host "STEP 6: GENERATE WEEKLY PERFORMANCE REPORT (AI INSIGHTS)" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray

try {
    $weeklyReportResult = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/performance-reports/$weeklyPlanId/generate" -Method Post -Headers $headers

    if ($weeklyReportResult.success) {
        Write-Host "   SUCCESS! Weekly Report Generated" -ForegroundColor Green
        Write-Host ""
        Write-Host "   Weekly Performance Report:" -ForegroundColor Yellow
        Write-Host "   Week Number: $($weeklyReportResult.data.weekNumber)" -ForegroundColor White
        Write-Host "   Performance Score: $($weeklyReportResult.data.performanceScore)%" -ForegroundColor White
        Write-Host ""
        Write-Host "   AI Insights:" -ForegroundColor Yellow
        Write-Host "   $($weeklyReportResult.data.insights)" -ForegroundColor White
        Write-Host ""
        Write-Host "   Recommendations:" -ForegroundColor Yellow
        Write-Host "   $($weeklyReportResult.data.recommendations)" -ForegroundColor White
        Write-Host ""
    } else {
        Write-Host "   FAILED: $($weeklyReportResult.message)" -ForegroundColor Red
        Write-Host ""
    }
} catch {
    Write-Host "   ERROR: $($_.Exception.Message)" -ForegroundColor Red
    if ($_.ErrorDetails) {
        Write-Host "   Details: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host ""
}

# Step 7: Generate Monthly Performance Report
Write-Host "STEP 7: GENERATE MONTHLY PERFORMANCE REPORT (ADVANCED AI)" -ForegroundColor Yellow
Write-Host "-" * 100 -ForegroundColor Gray

try {
    $monthlyReportResult = Invoke-RestMethod -Uri "$baseUrl/api/v1/manager/monthly-reports/$monthlyPlanId/generate" -Method Post -Headers $headers

    if ($monthlyReportResult.success) {
        Write-Host "   SUCCESS! Monthly Report Generated" -ForegroundColor Green
        Write-Host ""
        Write-Host "   Monthly Performance Report:" -ForegroundColor Yellow
        Write-Host "   Month: $($monthlyReportResult.data.month)" -ForegroundColor White
        Write-Host "   Overall Score: $($monthlyReportResult.data.overallScore)%" -ForegroundColor White
        Write-Host ""
        Write-Host "   Executive Summary:" -ForegroundColor Yellow
        Write-Host "   $($monthlyReportResult.data.executiveSummary)" -ForegroundColor White
        Write-Host ""
        Write-Host "   Key Insights:" -ForegroundColor Yellow
        Write-Host "   $($monthlyReportResult.data.keyInsights)" -ForegroundColor White
        Write-Host ""
        Write-Host "   Trend Analysis:" -ForegroundColor Yellow
        Write-Host "   $($monthlyReportResult.data.trendAnalysis)" -ForegroundColor White
        Write-Host ""
    } else {
        Write-Host "   FAILED: $($monthlyReportResult.message)" -ForegroundColor Red
        Write-Host ""
    }
} catch {
    Write-Host "   ERROR: $($_.Exception.Message)" -ForegroundColor Red
    if ($_.ErrorDetails) {
        Write-Host "   Details: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host ""
}

# Final Summary
Write-Host "=" * 100 -ForegroundColor Cyan
Write-Host "  GEMINI AI TESTING COMPLETE" -ForegroundColor Green
Write-Host "=" * 100 -ForegroundColor Cyan
Write-Host ""
Write-Host "All Gemini AI features have been tested!" -ForegroundColor Green
Write-Host ""
Write-Host "API Key: AIzaSyDWHGeWYyjJOoEsX3vG6y3wHAunpklMGYA" -ForegroundColor White
Write-Host "Model: gemini-2.5-flash" -ForegroundColor White
Write-Host ""
