# Test Annual Target Creation
$loginBody = @{
    emailOrPhone = "manager@rafeed.com"
    password = "manager123"
} | ConvertTo-Json

$loginResp = Invoke-RestMethod -Uri "http://localhost:5041/api/v1/auth/login" -Method Post -Body $loginBody -ContentType "application/json"
$token = $loginResp.token

$headers = @{
    "Authorization" = "Bearer $token"
    "Content-Type" = "application/json"
}

$body = @{
    targetYear = 2026
    totalTargetRevenue = 1000000.0
    description = "Annual revenue target for 2026"
} | ConvertTo-Json

Write-Host "Creating annual target with Gemini AI..." -ForegroundColor Cyan

try {
    $result = Invoke-RestMethod -Uri "http://localhost:5041/api/v1/manager/annual-targets" -Method Post -Headers $headers -Body $body

    Write-Host "SUCCESS!" -ForegroundColor Green
    Write-Host "Annual Target ID: $($result.data.id)" -ForegroundColor White
    Write-Host "Monthly Plans: $($result.data.monthlyPlans.Count)" -ForegroundColor White

    $weeklyCount = 0
    foreach ($month in $result.data.monthlyPlans) {
        $weeklyCount += $month.weeklyPlans.Count
    }
    Write-Host "Weekly Plans Generated by Gemini AI: $weeklyCount" -ForegroundColor Green

} catch {
    Write-Host "ERROR:" -ForegroundColor Red
    Write-Host $_.ErrorDetails.Message -ForegroundColor Red
}
